#!/bin/bash
#SBATCH -J LoFreqSNVCallingforPacBio
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=16100M
#SBATCH --output=/ifs/home/kevin/WGS/jobs/lofreq.out
#SBATCH --error=/ifs/home/kevin/WGS/jobs/lofreq.err
#SBATCH --partition=research
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=kevin.yauy@radboudumc.nl
/ifs/home/kevin/lofreq_star-2.1.3.1/bin/lofreq call-parallel --pp-threads 8 -f /ifs/home/kevin/WGS/data/GRCh38_no_alt_plus_hs38d1_concat_nonprimary.fa -s -S /ifs/home/kevin/WGS/data/common_all_20180418.vcf.gz --call-indels -o /ifs/home/kevin/WGS/data/Trio5_BvB41_child_DNA17-06166_PacBio_LoFreq.vcf /ifs/data/research/projects/sequel/bamfiles_hg38_20180822/hg38.PBRT05-p__DNA17-06166.bam

